'use strict';
const cheerio=require('cheerio');const {sanitize,plain,slugify,COMPLIANCE}=require('./rules.cjs');const {pillars}=require('./plan.json');
const SITE='https://homelistingai.com';
const {escapeHtml:esc,jsonLdSafe:json,breadcrumbJsonLd,renderRssXml}=require('./render-core.cjs');
const absolute=p=>/^https?:\/\//.test(p||'')?p:SITE+(p||'/og-image.png');
const AUTHOR={ '@type':'Person',name:'Chris Potter',url:SITE+'/blog/author/chris-potter',description:'Founder of HomeListingAI with 15 years in mortgage, including the 2007 and 2012 markets.' };
const ORG={'@type':'Organization',name:'HomeListingAI',url:SITE,logo:SITE+'/newlogo.png'};
function schema(post){return [
 {'@context':'https://schema.org','@type':'BlogPosting',headline:post.title,description:post.seo_description||post.excerpt,image:absolute(post.featured_image),url:SITE+'/blog/'+post.slug,datePublished:post.published_at||undefined,dateModified:post.updated_at||post.published_at||undefined,author:AUTHOR,publisher:ORG,mainEntityOfPage:SITE+'/blog/'+post.slug},
 JSON.parse(breadcrumbJsonLd(post,SITE)),
 ...(Array.isArray(post.faq)&&post.faq.length?[{'@context':'https://schema.org','@type':'FAQPage',mainEntity:post.faq.map(f=>({'@type':'Question',name:f.question,acceptedAnswer:{'@type':'Answer',text:f.answer}}))}]:[]),
 {'@context':'https://schema.org',...AUTHOR},{'@context':'https://schema.org',...ORG}];}
function shell({title,description='',route='/blog',image='/blog/assets/realtor-referrals.webp',body,noindex=false,schemas=[],slug=''}){return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><meta name="description" content="${esc(description)}"><meta name="robots" content="${noindex?'noindex,nofollow':'index,follow'}"><link rel="canonical" href="${SITE}${esc(route)}"><meta property="og:type" content="${slug?'article':'website'}"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="${SITE}${esc(route)}"><meta property="og:image" content="${esc(absolute(image))}"><meta property="og:image:width" content="1200"><meta property="og:image:height" content="630"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="${esc(title)}"><meta name="twitter:description" content="${esc(description)}"><meta name="twitter:image" content="${esc(absolute(image))}"><link rel="alternate" type="application/rss+xml" title="HomeListingAI Blog" href="/blog/rss.xml"><link rel="stylesheet" href="/blog/assets/blog.css">${schemas.map(s=>`<script type="application/ld+json">${json(s)}</script>`).join('')}<script src="/blog/assets/blog.js" defer></script></head><body data-slug="${esc(slug)}" data-preview="${noindex}"><a class="skip" href="#main">Skip to content</a><header class="site-header"><a class="brand" href="/"><img src="/newlogo.png" width="34" height="38" alt="">HomeListingAI</a><nav aria-label="Main"><a href="/blog">Field notes</a><a href="/tools/cost-per-closed-loan">Loan cost calculator</a><a class="button small" data-event="cta_click" data-trial href="/lo-signup?utm_source=blog&utm_medium=article&utm_campaign=${esc(slug||'index')}">Start free trial</a></nav></header>${body}<footer><a href="/blog/author/chris-potter">Written by Chris Potter</a><p>Built for this market. Practical ideas for loan officers and their agent partners.</p><a href="/privacy">Privacy</a> · <a href="/blog/rss.xml">RSS feed</a></footer></body></html>`;}
function cta(slug){const utm=`utm_source=blog&utm_medium=article&utm_campaign=${encodeURIComponent(slug)}`;return `<aside class="cta"><span class="eyebrow">YOUR NEXT CONVERSATION</span><h2>Warm leads, not cold calls.</h2><p>See a listing experience you can bring to your next agent conversation.</p><div class="actions"><a class="button" data-event="cta_click" data-trial href="/lo-signup?${utm}">Start free trial</a><a class="button secondary" data-event="cta_click" href="/for-loan-officers?${utm}">See a WOW Link demo</a></div></aside>`;}
function leadForm(magnet,slug){const names={'agent-partner-pitch':'Agent Partner Pitch Script','respa-checklist':'Co-Marketing Checklist','cost-per-closed-loan':'Your cost-per-closed-loan PDF'};return `<aside class="lead-magnet" id="worksheet"><span class="eyebrow">TAKE IT TO YOUR NEXT CALL</span><h2>${esc(names[magnet]||names['agent-partner-pitch'])}</h2><p>Get the worksheet. Useful even if you never buy anything.</p><form data-lead-form data-magnet="${esc(magnet)}" data-article="${esc(slug)}"><label>Your name<input name="name" autocomplete="name" maxlength="100" required></label><label>Email address<input name="email" type="email" autocomplete="email" maxlength="254" required></label><label class="trap" aria-hidden="true">Leave this empty<input name="website" tabindex="-1" autocomplete="off"></label><label class="consent"><input type="checkbox" name="consent" required>Save my details to provide this download. No text-message consent or newsletter subscription. <a href="/privacy">Privacy policy</a></label><button class="button" type="submit">Get the free worksheet</button><p role="status" aria-live="polite"></p></form></aside>`;}
function date(value){return value?new Date(value).toLocaleDateString('en-US',{month:'long',day:'numeric',year:'numeric',timeZone:'America/Los_Angeles'}):'Draft for review';}
function article(post,related=[],{preview=false}={}){
 const $=cheerio.load(sanitize(post.content),null,false),toc=[];
 $('h2').each((i,el)=>{const id=`section-${i+1}-${slugify($(el).text())}`;$(el).attr('id',id);toc.push({id,title:$(el).text()});});
 // Planned links to unpublished material must never lead visitors to private drafts.
 const liveSlugs=new Set(related.filter(p=>p.status==='published').map(p=>p.slug));
 if(!preview)$('a[href^="/blog/"]').each((_,el)=>{const slug=$(el).attr('href').slice(6);if(!liveSlugs.has(slug))$(el).replaceWith($(el).contents());});
 const mid=Math.floor(toc.length/2);const sections=$('h2').toArray();if(sections[mid])$(sections[mid]).before(leadForm(post.lead_magnet||'agent-partner-pitch',post.slug));
 const body=`<main id="main" class="reading">${preview?'<p class="draft-banner">PRIVATE DRAFT · Nothing here has been published.</p>':''}<a class="back" href="/blog">← Field notes</a><header class="article-header"><a class="eyebrow" href="/blog/topic/${esc(post.pillar||'lo-marketing')}">${esc(pillars.find(p=>p.slug===post.pillar)?.title||'Loan officer field notes')}</a><h1>${esc(post.title)}</h1><div class="byline"><a href="/blog/author/chris-potter">Chris Potter</a><span>${date(post.published_at)}</span><span>Updated ${date(post.updated_at)}</span><span>${post.reading_minutes||Math.ceil(plain(post.content).split(/\s+/).length/220)} min read</span></div></header>${post.featured_image?`<img class="hero-image" src="${esc(post.featured_image)}" width="1200" height="630" alt="${esc(post.featured_image_alt||post.title)}" fetchpriority="high">`:''}<aside class="short-answer"><h2>The short answer</h2><p>${esc(post.short_answer||post.excerpt)}</p></aside><details class="toc" open><summary>On this page</summary><ol>${toc.map(t=>`<li><a href="#${esc(t.id)}">${esc(t.title)}</a></li>`).join('')}</ol></details><div class="article-body">${$.html()}</div>${post.faq?.length?`<section class="faq"><h2>Questions loan officers ask</h2>${post.faq.map(f=>`<h3>${esc(f.question)}</h3><p>${esc(f.answer)}</p>`).join('')}</section>`:''}${post.compliance_note&&!plain(post.content).includes(COMPLIANCE)?`<p class="compliance">${COMPLIANCE}</p>`:''}${cta(post.slug)}<aside class="sticky-cta" hidden aria-label="Try HomeListingAI"><a class="button small" data-event="cta_click" data-trial href="/lo-signup?utm_source=blog&utm_medium=article&utm_campaign=${esc(post.slug)}">Start free trial</a><a class="text-link" data-event="cta_click" href="/for-loan-officers?utm_source=blog&utm_medium=article&utm_campaign=${esc(post.slug)}">WOW Link demo</a><button type="button" data-dismiss-cta aria-label="Dismiss trial reminder">×</button></aside><section class="related"><h2>Keep building your playbook</h2>${cards(related.filter(p=>(post.related_slugs||[]).includes(p.slug)&&p.slug!==post.slug&&(preview||p.status==='published')).slice(0,4))}</section><nav class="share" aria-label="Share article"><a target="_blank" rel="noopener" href="https://www.linkedin.com/sharing/share-offsite/?url=${encodeURIComponent(SITE+'/blog/'+post.slug)}">Share on LinkedIn</a><a target="_blank" rel="noopener" href="https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(SITE+'/blog/'+post.slug)}">Facebook</a><a href="mailto:?subject=${encodeURIComponent(post.title)}&body=${encodeURIComponent(SITE+'/blog/'+post.slug)}">Email</a><button type="button" data-copy-link>Copy link</button></nav></main>`;
 return shell({title:post.seo_title||post.title,description:post.seo_description||post.excerpt,route:'/blog/'+post.slug,image:post.featured_image,body,noindex:preview,schemas:schema(post),slug:post.slug});
}
function cards(posts){return `<div class="cards">${posts.map(p=>`<article class="card" data-title="${esc(p.title.toLowerCase())}" data-pillar="${esc(p.pillar)}">${p.featured_image?`<img src="${esc(p.featured_image)}" width="1200" height="630" alt="${esc(p.featured_image_alt||p.title)}" loading="lazy">`:''}<span class="eyebrow">${p.role==='hub'?'Complete guide':'Field note'}</span><h3><a href="/blog/${esc(p.slug)}">${esc(p.title)}</a></h3><p>${esc(p.excerpt||'Practical steps for your next agent or buyer conversation.')}</p><span class="meta">${date(p.published_at)}</span></article>`).join('')}</div>`;}
function index(posts,pillar=null){const filtered=posts.filter(p=>p.status==='published'&&p.role!=='tool'&&(!pillar||p.pillar===pillar));const hubs=filtered.filter(p=>p.role==='hub'),spokes=filtered.filter(p=>p.role!=='hub');const title=pillars.find(p=>p.slug===pillar)?.title||'Field notes for the next warm lead.';return shell({title:pillar?title+' | HomeListingAI':'Loan Officer Blog | HomeListingAI',description:'Practical guides for loan officers: stronger agent partnerships, warmer conversations, useful marketing and honest AI advice.',route:pillar?'/blog/topic/'+pillar:'/blog',body:`<main id="main" class="wide"><section class="index-hero"><span class="eyebrow">THE LO PLAYBOOK</span><h1>${esc(title)}</h1><p>Bring something useful to your next agent conversation.<br>Plain words. Actual scripts. Built for this market.</p><a class="text-link" href="/blog/author/chris-potter">By Chris Potter · 15 years in mortgage →</a></section><nav class="pillars" aria-label="Topics"><a href="/blog">All topics</a>${pillars.map(p=>`<a href="/blog/topic/${p.slug}" ${p.slug===pillar?'aria-current="page"':''}>${esc(p.title)}</a>`).join('')}</nav><label class="search">Find a field note<input type="search" data-search placeholder="Agent referrals, AI, follow-up…"></label>${hubs.length?'<section><h2>Start with a complete guide</h2>'+cards(hubs)+'</section>':''}<section><h2>Latest field notes</h2>${spokes.length?cards(spokes):'<p>New guides are being reviewed. Try the free loan cost calculator while they are prepared.</p>'}<p data-no-results hidden>No matching articles. Try another search.</p></section>${cta(pillar||'index')}</main>`});}
function author(){return shell({title:'Chris Potter | HomeListingAI Blog',route:'/blog/author/chris-potter',description:'Chris Potter, founder of HomeListingAI, writes practical field notes for loan officers with 15 years of mortgage experience.',schemas:[{'@context':'https://schema.org',...AUTHOR}],body:`<main id="main" class="reading"><span class="eyebrow">THE PERSON BEHIND THE PLAYBOOK</span><h1>Chris Potter</h1><p class="intro">15 years in mortgage. Built for this market.</p><p>I’m the founder of HomeListingAI. I’ve worked through 2007, 2012, and the market we’re in now.</p><p>This blog is for loan officers who want warm conversations and agent partners who call them first. Expect useful scripts, plain explanations, and steps you can try before buying anything.</p><p>My focus is simple: help loan officers bring something useful to their agent partners and turn listing questions into conversations.</p><a class="button" href="/blog">Read the field notes</a></main>`});}
function calculator(){return shell({title:'Cost per Closed Loan Calculator | HomeListingAI',route:'/tools/cost-per-closed-loan',description:'Calculate marketing cost per funded loan using your own costs and closed-loan count. Compare channels and download a free worksheet.',body:`<main id="main" class="reading"><span class="eyebrow">USE YOUR OWN NUMBERS</span><h1>What did that closed loan really cost?</h1><p>Use the same time period for every number. This measures acquisition cost, not profit or a promised return.</p><form data-calculator><label>Marketing spend ($)<input name="spend" type="number" min="0" max="100000000" step="0.01" value="0" required></label><label>Staff time and other acquisition costs ($)<input name="other" type="number" min="0" max="100000000" step="0.01" value="0" required></label><label>Loans funded from those efforts<input name="closed" type="number" min="0" max="1000000" step="1" value="0" required></label><button class="button" type="submit">Calculate</button><output aria-live="polite">Add your numbers to see the result.</output></form><h2>The math</h2><p>(Marketing spend + acquisition costs) ÷ funded loans. With zero funded loans, there is no finite cost per closed loan yet.</p><p>Example only: $1,200 marketing + $300 staff cost, divided by 3 funded loans = $500 per loan. These are sample inputs, not customer results.</p>${leadForm('cost-per-closed-loan','cost-per-closed-loan')}</main>`});}
function rss(posts){return renderRssXml(posts.filter(p=>p.status==='published'&&p.role!=='tool'),{siteOrigin:SITE});}
function sitemap(posts,base=''){const urls=['/blog','/blog/author/chris-potter','/tools/cost-per-closed-loan',...pillars.map(p=>'/blog/topic/'+p.slug)];const latest=posts.filter(p=>p.status==='published').map(p=>p.updated_at||p.published_at).filter(Boolean).sort().at(-1)||'2026-10-05T00:00:00Z';const entries=urls.map(route=>`<url><loc>${SITE}${route}</loc><lastmod>${esc(new Date(latest).toISOString())}</lastmod></url>`).concat(posts.filter(p=>p.status==='published'&&p.role!=='tool').map(p=>`<url><loc>${SITE}/blog/${esc(p.slug)}</loc><lastmod>${esc(new Date(p.updated_at||p.published_at).toISOString())}</lastmod></url>`));const old=base.match(/<url>[^]*?<\/url>/g)||[];return `<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${old.filter(s=>!/<loc>[^<]*\/(blog(?:\/|<)|tools\/cost-per-closed-loan)/.test(s)).join('')}${entries.join('')}</urlset>`;}
module.exports={shell,article,index,author,calculator,schema,rss,sitemap,esc,SITE};
