import React, { useEffect, useState } from 'react';
import { adminMarketingMediaService as api, type ImageCatalog, type MarketingImage, type ImagePerformance } from '../../services/adminMarketingMediaService';
import { adminMarketingStudioService, type StudioCampaign } from '../../services/adminMarketingStudioService';
const button='min-h-11 rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm font-semibold text-slate-700 disabled:opacity-50';
const primary='min-h-11 rounded-lg bg-primary-600 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50';
const input='mt-1 w-full rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm text-slate-800';
const REVIEW=[['real','Real-looking?'],['idea','One idea?'],['brand','Matches brand?'],['honest','Nothing misleading?']] as const;
export default function MarketingImageLibrary({campaign,onChange,disabled=false,photoUploaded=false}:{campaign?:StudioCampaign;onChange?:(row:StudioCampaign)=>void;disabled?:boolean;photoUploaded?:boolean}) {
  const [catalog,setCatalog]=useState<ImageCatalog>();const [images,setImages]=useState<MarketingImage[]>([]);const [format,setFormat]=useState('blog');const [recipe,setRecipe]=useState('');
  const [headline,setHeadline]=useState('');const [subline,setSubline]=useState('');const [tweak,setTweak]=useState('');const [selected,setSelected]=useState('');const [review,setReview]=useState<Record<string,boolean>>({});const [busy,setBusy]=useState(false);const [pending,setPending]=useState('');const [error,setError]=useState('');const [message,setMessage]=useState('');const [filter,setFilter]=useState('all');
  const [results,setResults]=useState<ImagePerformance[]>([]);
  const [lending,setLending]=useState(false);
  useEffect(()=>{if(campaign)return;let active=true;api.imageResults().then(rows=>{if(active)setResults(rows);}).catch(()=>{});return()=>{active=false;};},[campaign]);
  useEffect(()=>{let active=true;Promise.all([api.imageCatalog(),api.imageLibrary()]).then(([c,rows])=>{if(active){setCatalog(c);setImages(rows);}}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[campaign?.id]);
  useEffect(()=>{if(!pending)return;let active=true;const started=Date.now();const timer=window.setInterval(async()=>{try{const rows=await api.imageLibrary();if(!active)return;setImages(rows);const media=campaign?await api.list(campaign.id):[];if(!media.some(m=>m.kind==='image'&&m.status==='processing')){setPending('');setBusy(false);if(!rows.some(r=>r.group_id===pending))setError(media.find(m=>m.kind==='image')?.error||'No choices were saved. Try again.');}else if(Date.now()-started>600000){setPending('');setBusy(false);setError('This is taking longer than usual. Reload to check saved choices.');}}catch(e){if(active){setError(e instanceof Error?e.message:'Could not load pictures.');setBusy(false);setPending('');}}},3000);return()=>{active=false;window.clearInterval(timer);};},[pending,campaign]);
  async function refreshCampaign(){const rows=await adminMarketingStudioService.list();const latest=rows.find(r=>r.id===campaign?.id);if(latest)onChange?.(latest);}
  async function make(image?:MarketingImage,final=false){if(!campaign)return;setBusy(true);setError('');setMessage('');try{const data=await api.imageOptions(campaign,{format,recipeId:recipe||undefined,headline,subline,requiresLending:lending,...(image?{imageId:image.id,tweak,final}:{})});setPending(data.groupId);await refreshCampaign();}catch(e){setError(e instanceof Error?e.message:'Could not make these choices.');setBusy(false);}}
  async function choose(){if(!selected)return;setBusy(true);setError('');try{if(campaign)await api.chooseImage(campaign,selected,review,['blog','og'].includes(images.find(r=>r.id===selected)?.format||'')?'blog':images.find(r=>r.id===selected)?.format==='email'?'email':'campaign');else await api.reviewImage(selected,review);setImages(await api.imageLibrary());if(campaign)await refreshCampaign();setMessage(campaign?'Saved to your campaign. Nothing was published.':'Checked and saved to your library. Nothing was published.');}catch(e){setError(e instanceof Error?e.message:'Could not use this picture.');}finally{setBusy(false);}}
  async function layout(){if(!campaign||!selected)return;setBusy(true);setError('');try{await api.imageLayout(campaign,selected,{format,headline,subline});setImages(await api.imageLibrary());setMessage('New size and words saved. Check the new choice before using it.');}catch(e){setError(e instanceof Error?e.message:'Could not update the layout.');}finally{setBusy(false);}}
  async function samples(){setBusy(true);setError('');try{const loaded=await api.loadImageSamples();setImages(await api.imageLibrary());setMessage(loaded.added?'Your sample choices are ready to review.':'Your sample choices are already saved.');}catch(e){setError(e instanceof Error?e.message:'Could not load samples.');}finally{setBusy(false);}}
  const choice=images.find(r=>r.id===selected);const cost=catalog?.costs[format];
  const rows=images.filter(r=>(!campaign||r.campaign_id===campaign.id||r.approved)&&(filter==='all'||filter==='saved'&&r.approved||filter==='review'&&!r.approved));
  return <section aria-label="Picture library" className="mt-5 rounded-2xl border border-slate-200 bg-white p-4 sm:p-5">
    <h3 className="text-xl font-bold text-slate-900">{campaign?'Make your picture':'Picture library'}</h3><p className="mt-1 text-sm text-slate-600">Real scenes, clean words, your logo. Every picture waits for your review.</p>
    {error&&<p role="alert" className="mt-3 rounded-lg bg-red-50 p-3 text-sm text-red-800">{error}</p>}{message&&<p role="status" className="mt-3 text-sm text-green-700">{message}</p>}
    {!campaign&&<button type="button" className={`${button} mt-4`} disabled={busy} onClick={samples}>Load sample ideas · free</button>}
    {campaign&&<div className="mt-4 grid gap-3 sm:grid-cols-2">
      <label className="text-sm font-semibold">Picture size<select className={input} value={format} onChange={e=>setFormat(e.target.value)} disabled={busy||disabled}>{Object.entries(catalog?.formats||{blog:{label:'Blog hero',width:1536,height:1024}}).map(([id,f])=><option key={id} value={id}>{f.label} · {f.width} × {f.height}</option>)}</select></label>
      <label className="text-sm font-semibold">Scene<select className={input} value={recipe} onChange={e=>{setRecipe(e.target.value);setLending(catalog?.recipes.find(r=>r.id===e.target.value)?.use==='paid_ad');}} disabled={busy||disabled}><option value="">Choose a scene for me</option>{catalog?.recipes.map(r=><option key={r.id} value={r.id}>{r.use} · {r.pillar} · {r.subject}</option>)}</select></label>
      <label className="text-sm font-semibold">Headline (up to 8 words)<input className={input} value={headline} maxLength={120} onChange={e=>setHeadline(e.target.value)} disabled={busy||disabled} placeholder="A warmer way to find your next lead" /></label>
      <label className="text-sm font-semibold">Small line (optional)<input className={input} value={subline} maxLength={90} onChange={e=>setSubline(e.target.value)} disabled={busy||disabled} /></label>
      {catalog?.recipes.find(r=>r.id===recipe)?.use==='paid_ad'&&<div className="sm:col-span-2"><label className="flex min-h-11 items-center gap-2 text-sm"><input type="checkbox" checked={lending} onChange={e=>setLending(e.target.checked)} />This advertises a loan or lending service</label>{lending&&<p className="text-sm text-amber-800">This needs your official lender badge and verified NMLS number first.</p>}</div>}
      <div className="sm:col-span-2"><p className="text-sm text-slate-600">Three draft choices: about ${cost?.set.toFixed(3)||'0.045'} total, plus small prompt and picture-check charges. One tweak: about ${cost?.one.toFixed(3)||'0.015'}. A chosen final: about ${cost?.final.toFixed(3)||'0.052'}, plus its reference photo charge. Up to three paid requests per campaign.</p><button className={`${primary} mt-3`} type="button" disabled={busy||disabled||(campaign.pictureMode==='own'||photoUploaded)||!catalog} onClick={()=>make()}>{busy?'Making your choices…':'Make three choices'}</button>{(campaign.pictureMode==='own'||photoUploaded)&&<p className="mt-2 text-sm text-slate-600">You chose your own photo. Use the upload button above; it costs nothing.</p>}</div>
    </div>}
    <label className="mt-5 block text-sm font-semibold">Show<select className={`${input} max-w-xs`} value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All pictures</option><option value="saved">Checked and saved</option><option value="review">Waiting for review</option></select></label>
    <div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{rows.map(r=><button type="button" key={r.id} className={`overflow-hidden rounded-xl border-2 bg-slate-50 text-left ${selected===r.id?'border-primary-600':'border-slate-200'}`} onClick={()=>{setSelected(r.id);setFormat(r.format);setRecipe(r.recipe_id);setHeadline(r.settings?.headline||r.headline||'');setSubline(r.settings?.subline||'');setReview({});setTweak('');}} aria-pressed={selected===r.id}><img src={r.url} alt={r.alt_text} className="aspect-video w-full object-contain" /><div className="p-3"><p className="text-sm font-semibold text-slate-800">{catalog?.recipes.find(s=>s.id===r.recipe_id)?.pillar||'Editorial scene'} · Choice {r.variant+1}</p><p className="mt-1 text-xs text-slate-600">{r.width} × {r.height} · {r.approved?'Saved':'Review first'}</p>{r.checks.problems.length>0&&<p className="mt-2 text-xs text-red-700">{r.checks.problems[0]}</p>}</div></button>)}</div>
    {!rows.length&&!busy&&<p className="mt-4 text-sm text-slate-600">Your saved choices will appear here. Make them from a campaign first.</p>}
    {choice&&<div className="mt-5 rounded-xl bg-slate-50 p-4"><h4 className="font-bold">Review your choice</h4><img src={choice.url} alt={choice.alt_text} className="mt-3 max-h-[600px] w-full rounded-lg object-contain" /><a href={choice.url} target="_blank" rel="noreferrer" className={`${button} mt-3 inline-flex`}>Open full picture</a><p className="mt-2 text-sm text-slate-600">{choice.alt_text}</p>{choice.checks.problems.map(p=><p className="mt-2 text-sm text-red-700" key={p}>{p}</p>)}<div className="mt-3 flex flex-wrap gap-4">{REVIEW.map(([key,label])=><label key={key} className="flex min-h-11 items-center gap-2 text-sm"><input type="checkbox" checked={Boolean(review[key])} onChange={e=>setReview({...review,[key]:e.target.checked})} />{label}</label>)}</div>
      {campaign?<><button type="button" className={`${primary} mt-3`} disabled={busy||disabled||choice.checks.problems.length>0||!REVIEW.every(([k])=>review[k])} onClick={choose}>Use this</button><button type="button" className={`${button} ml-2 mt-3`} disabled={busy||disabled} onClick={layout}>Apply size and words · free</button><label className="mt-4 block text-sm font-semibold">Tweak this choice<input className={input} placeholder="Warmer, less busy, move the person left…" value={tweak} maxLength={500} onChange={e=>setTweak(e.target.value)} /></label><div className="mt-3 flex flex-wrap gap-2"><button type="button" className={button} disabled={busy||disabled||choice.campaign_id!==campaign.id} onClick={()=>make(choice)}>Regenerate this choice</button><button type="button" className={button} disabled={busy||disabled||!choice.approved||choice.campaign_id!==campaign.id} onClick={()=>make(choice,true)}>Make high-quality final</button></div></>:<button type="button" className={`${primary} mt-3`} disabled={busy||choice.checks.problems.length>0||!REVIEW.every(([k])=>review[k])} onClick={choose}>Use this</button>}
    </div>}
    {!campaign&&<div className="mt-6"><h4 className="font-bold text-slate-800">Best performing scenes</h4>{results.length?results.map(r=><div className="mt-2 rounded-lg bg-slate-50 p-3 text-sm" key={r.recipe_id}><p className="font-semibold">{catalog?.recipes.find(s=>s.id===r.recipe_id)?.pillar||r.recipe_id} · {r.mood} · {r.text_zone}</p><p>{r.views} article views · {r.clicks} button clicks · {r.engagement} deep reads · {r.ctr===null?'No click rate yet':`${(r.ctr*100).toFixed(1)}% button click rate`}</p></div>):<p className="mt-2 text-sm text-slate-500">Your results will appear after a blog uses a checked picture and receives visits. Social results wait until accounts are connected.</p>}</div>}
  </section>;
}
