'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');const cheerio=require('cheerio');
const rules=require('../blog/rules.cjs'),render=require('../blog/render.cjs'),{createBlogService,pdf}=require('../blog/service.cjs'),plan=require('../blog/plan.json');
const OWNER='11111111-1111-4111-8111-111111111111';
function memory(rows=[]){const stores={blog_posts:rows,leads:[],blog_events:[],blog_settings:[{id:1,lead_owner_id:OWNER}],admin_marketing_campaigns:[]};return {stores,from(name){let conditions=[],action=null,payload=null,single=false;const q={select(){return q;},eq(k,v){conditions.push(x=>x[k]===v);return q;},lte(k,v){conditions.push(x=>x[k]<=v);return q;},limit(){return q;},order(){return q;},maybeSingle(){single=true;return q;},single(){single=true;return q;},insert(p){action='insert';payload=p;return q;},update(p){action='update';payload=p;return q;},upsert(p){action='upsert';payload=p;return q;},then(resolve){let data=(stores[name]||[]).filter(x=>conditions.every(c=>c(x)));if(action==='insert'||action==='upsert'){data=Array.isArray(payload)?payload:[payload];stores[name].push(...data);}if(action==='update')data.forEach(x=>Object.assign(x,payload));return Promise.resolve({data:single?data[0]||null:data,error:null}).then(resolve);}};return q;}};}
function fixture(){const file=fs.readdirSync(path.join(__dirname,'../blog/content')).find(f=>f.endsWith('.json'));return {...JSON.parse(fs.readFileSync(path.join(__dirname,'../blog/content',file))),id:OWNER,updated_at:'2026-10-05T12:00:00.000Z'};}
test('editorial slugs are unique and all spokes point to real hubs',()=>{const slugs=plan.posts.map(p=>p.slug);assert.equal(new Set(slugs).size,36);assert.equal(plan.posts.filter(p=>p.role==='hub').length,5);for(const p of plan.posts.filter(p=>p.role==='spoke'))assert.ok(slugs.includes(p.hub_slug));});
test('ten complete starter drafts pass the publishing checks',()=>{const files=fs.readdirSync(path.join(__dirname,'../blog/content')).filter(f=>f.endsWith('.json'));assert.equal(files.length,10);for(const file of files){const p=JSON.parse(fs.readFileSync(path.join(__dirname,'../blog/content',file)));assert.equal(p.status,'draft');assert.equal(rules.checks(p).ok,true,file+': '+rules.checks(p).errors.join(';'));}});
test('checks block banned words, short copy, missing links and missing compliance',()=>{const p=fixture();const review=rules.checks({...p,content:'<h2>Overview</h2><p>A revolutionary solution.</p>',faq:[],seo_description:'short',featured_image_alt:''});assert.equal(review.ok,false);assert.ok(review.errors.some(e=>e.includes('banned phrase')));assert.ok(review.errors.some(e=>e.includes('compliance')));});
test('sanitization removes executable HTML and unsafe protocols',()=>{const clean=rules.sanitize('<script>alert(1)</script><p onclick="bad()">safe</p><a href="javascript:alert(1)">link</a><img src="data:text/html,evil" onerror="bad()">');assert.ok(!clean.includes('script'));assert.ok(!clean.includes('onclick'));assert.ok(!clean.includes('javascript:'));assert.ok(!clean.includes('onerror'));});
test('schema and first HTML response contain article text, author, FAQ and metadata',()=>{const p=fixture();const html=render.article(p,[],{preview:true}),$=cheerio.load(html);assert.equal($('h1').text(),p.title);assert.ok($('.article-body').text().length>4000);assert.equal($('meta[name=robots]').attr('content'),'noindex,nofollow');const data=$('script[type="application/ld+json"]').map((_,e)=>JSON.parse($(e).html())).get();assert.ok(data.some(s=>s['@type']==='FAQPage'));assert.equal(data.find(s=>s['@type']==='BlogPosting').author.name,'Chris Potter');assert.equal($('link[rel=canonical]').attr('href'),'https://homelistingai.com/blog/'+p.slug);assert.ok($('h2[id]').length>=5);});
test('sitemap and RSS never expose draft, brief or scheduled articles',()=>{const posts=['draft','brief','scheduled','published'].map(status=>({slug:status,status,title:status,updated_at:'2026-10-05T00:00:00Z',published_at:'2026-10-05T00:00:00Z'}));const xml=render.sitemap(posts);assert.ok(xml.includes('/blog/published'));for(const s of ['draft','brief','scheduled'])assert.ok(!xml.includes('/blog/'+s));assert.ok(!render.rss(posts).includes('/blog/draft'));});
test('publishing is blocked server-side and drafts remain editable',async()=>{const row=fixture(),db=memory([row]),service=createBlogService({db});await assert.rejects(service.save(OWNER,{...row,status:'published',content:'too short'}),e=>e.status===422);assert.equal(row.status,'draft');const saved=await service.save(OWNER,{...row,status:'draft',content:'<p>Work in progress</p>'});assert.equal(saved.post.status,'draft');assert.ok(saved.review.errors.length>0);});
test('saving a stale version cannot overwrite newer edits',async()=>{const row=fixture(),service=createBlogService({db:memory([row])});await assert.rejects(service.save(OWNER,{...row,updated_at:'old',status:'draft'}),e=>e.status===409);});
test('publishing creates linked sharing drafts, not social posts',async()=>{const p=fixture(),db=memory([p]);const service=createBlogService({db,now:()=> '2026-10-05T13:00:00.000Z'});await service.save(OWNER,{...p,status:'published'});assert.equal(db.stores.admin_marketing_campaigns.length,1);const draft=db.stores.admin_marketing_campaigns[0];assert.match(draft.id,/^[0-9a-f-]{36}$/);assert.equal(draft.status,'draft');assert.equal(draft.blog_post_id,p.id);assert.equal(draft.brief.quoteCards.length,3);assert.ok(draft.outputs.linkedin.includes('/blog/'));});
test('invalid scheduled copy returns to draft instead of publishing',async()=>{const p={...fixture(),status:'scheduled',scheduled_at:'2026-01-01',content:'short'},db=memory([p]),service=createBlogService({db});await service.publishDue();assert.equal(p.status,'draft');assert.ok(p.review_errors.length>0);});
test('lead capture requires consent, uses the platform owner, and returns a signed PDF',async()=>{const db=memory(),service=createBlogService({db,env:{BLOG_DOWNLOAD_SECRET:'test-only-secret'}});await assert.rejects(service.lead({name:'Test',email:'test@example.test',magnet:'cost-per-closed-loan',slug:'cost-per-closed-loan'}),e=>e.status===400);const r=await service.lead({name:'Test',email:'test@example.test',consent:true,magnet:'cost-per-closed-loan',slug:'cost-per-closed-loan',user_id:'attacker',calculator:{spend:1200,other:300,closed:3}});assert.equal(db.stores.leads[0].user_id,OWNER);assert.equal(db.stores.leads[0].source,'blog');assert.equal(db.stores.leads[0].consent_sms,false);const token=r.download.split('/').at(-1),bytes=service.download(token);assert.ok(bytes.toString().startsWith('%PDF-1.4'));assert.ok(bytes.toString().includes('$500.00'));assert.throws(()=>service.download(token+'x'),e=>e.status===403);});
test('expired download tokens are rejected',async()=>{const db=memory();let now='2026-01-01T00:00:00Z';const service=createBlogService({db,env:{BLOG_DOWNLOAD_SECRET:'test'},now:()=>now});const r=await service.lead({name:'Test',email:'test@example.test',consent:true,magnet:'cost-per-closed-loan',slug:'cost-per-closed-loan'});now='2026-01-02T00:00:00Z';assert.throws(()=>service.download(r.download.split('/').at(-1)),e=>e.status===403);});
test('PDF text cannot inject PDF drawing commands',()=>{const result=pdf(['Text (quote) \\']);assert.ok(result.toString().includes('\\(quote\\)'));});

test('short answers reject early product names and more than four sentences',()=>{const p=fixture();assert.ok(rules.checks({...p,short_answer:'HomeListingAI helps here. Keep it practical.'}).errors.some(e=>e.includes('second half')));assert.ok(rules.checks({...p,short_answer:'One. Two. Three. Four. Five.'}).errors.some(e=>e.includes('2–4')));});

test('publication adds two incoming links without touching other topics',async()=>{const fresh=fixture(),older=[1,2,3].map(i=>({...fixture(),id:'older-'+i,slug:'older-'+i,status:'published',published_at:'2026-01-01T00:00:00Z',related_slugs:[],pillar:i===3?'unrelated':fresh.pillar})),db=memory([fresh,...older]);await createBlogService({db,now:()=> '2026-10-05T13:00:00.000Z'}).save(OWNER,{...fresh,status:'published'});for(const p of older.slice(0,2)){assert.ok(p.content.includes('/blog/'+fresh.slug));assert.ok(p.related_slugs.includes(fresh.slug));}assert.ok(!older[2].related_slugs.includes(fresh.slug));});
test('checked scheduled copy publishes once and failed search notification does not lose the save',async()=>{const p={...fixture(),status:'scheduled',author_id:OWNER,scheduled_at:'2026-01-01'},db=memory([p]),service=createBlogService({db,env:{INDEXNOW_KEY:'test-key'},fetchImpl:async()=>{throw Error('offline');},now:()=> '2026-10-05T13:00:00.000Z'});await service.publishDue();await service.publishDue();assert.equal(p.status,'published');assert.equal(db.stores.admin_marketing_campaigns.length,1);const result=await service.save(OWNER,{...p,status:'published'});assert.equal(result.distribution.indexNow,'failed');assert.equal(result.post.status,'published');});
