#!/bin/sh
. "$(git rev-parse --show-toplevel)/.husky/_/husky.sh"

npm run lint && npm run typecheck

# staged checks
if command -v npx >/dev/null 2>&1; then
	npx lint-staged
else
	"$(npm bin)/lint-staged"
fi
